# -*- coding: utf-8 -*-
"""Untitled182.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsxwrbrRhh7a8Zpxlwvld09jM9EQPcDU
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions



df =pd.read_excel("/content/salary_prediction (1).xlsx")

df.head() # on there we use the knearest neighbours algorithm used in the classfication
#nature of data kn algorithm will work on both analysis but they will work on the non linearty dataset

x=df.iloc[: , :-1]
y=["salary"]

from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

x_ =sc.fit_transform(x)
x =pd.DataFrame(x_, columns=x.columns)
x



from sklearn.model_selection import train_test_split
y = df['salary']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)



from sklearn.neighbors import KNeighborsClassifier

KNN = KNeighborsClassifier(n_neighbors=6)



KNN = KNeighborsClassifier(n_neighbors=8)
KNN.fit(x_train,y_train)

(KNN.score(x_test,y_test) ) *100
# there on will came very much more poor acurracy



(KNN.score(x_train,y_train) ) *100

KNN.predict([[-0.927452	,-0.671506]])

for i in range(1, len(x_train) + 1):
  KNN1= KNeighborsClassifier(n_neighbors=i)
  KNN1.fit(x_train,y_train)
  print(i,KNN1.score(x_test,y_test),KNN1.score(x_train,y_train))

#that model will check that give very much more poor accuracy so prediction will came wrong

plot_decision_regions(x.to_numpy(),y.to_numpy(), clf =KNN)
plt.show()

